### ISSUE TITLE
Optimize Sass code

### ISSUE THREAD

**Issue by pankajparashar-zz** [mrmrs/pesticide#19]
I feel that the Sass [code](https://github.com/mrmrs/pesticide/blob/master/sass/pesticide.scss) can be massively optimized by using the [Sass maps](http://blog.sass-lang.com/posts/184094-sass-33-is-released) that were introduced in version 3.3.

For example,
We can create a map that has **selector** as the _key_ and the corresponding _value_ as the **Hex color**.

``` css
$pesticide-map: (body: #2980b9, article: #3498db, nav: #0088c3, aside: #33a0ce);
```

And, then run a loop on this map to compute the final CSS.

``` css
@each $selector, $color in $pesticide-map {
    #{$selector} { outline: 1px solid #{$color} !important; }
}
```

This will produce the following output CSS,

``` css
body { outline: 1px solid #2980b9 !important; }
article { outline: 1px solid #3498db !important; }
nav { outline: 1px solid #0088c3 !important; }
aside { outline: 1px solid #33a0ce !important; }
```

This data structure will make the code much shorter/compact and would be very easy to maintain or add new elements in the code.

Any thoughts?
